We can create a NumPy ndarray object by using the array() function

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])

arr


array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

Create a 0-D array with value 42

In [4]:
arr = np.array(42)
arr

array(42)

Create a 1-D array containing the values 1,2,3,4,5

In [5]:
arr = np.array([1,2,3,4,5])

arr

array([1, 2, 3, 4, 5])

Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])